# Generated by Django 4.2.6 on 2023-10-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
        ('invoice', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='tax.tax'),
        ),
    ]
