# Generated by Django 4.2.6 on 2023-11-01 10:52

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_historicallistprice_options_and_more'),
        ('customer', '0003_alter_customer_address_alter_customer_email_and_more'),
        ('tax', '0003_alter_historicaltax_options_and_more'),
        ('invoice', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinvoice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Factura', 'verbose_name_plural': 'historical Facturas'},
        ),
        migrations.AlterModelOptions(
            name='historicalinvoiceitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Item de Factura', 'verbose_name_plural': 'historical Items de Factura'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-invoice_number'], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['-created'], 'verbose_name': 'Item de Factura', 'verbose_name_plural': 'Items de Factura'},
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='customer',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_number',
            field=models.IntegerField(verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje', max_digits=5, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitem',
            name='invoice',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='invoice.invoice', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitem',
            name='product',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customer.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='tax.tax', verbose_name='Impuestos'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje', max_digits=5, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
