# Generated by Django 4.2.6 on 2023-11-01 18:45

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_historicalproduct_options_and_more'),
        ('invoice', '0005_alter_historicalinvoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_number',
            field=models.IntegerField(verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='historicalinvoiceitem',
            name='product',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='product.product', verbose_name='Productos'),
        ),
    ]
