# Generated by Django 4.2.6 on 2023-11-01 19:03

from django.db import migrations
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_tax_number_and_more'),
        ('invoice', '0006_alter_historicalinvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='company',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='company.company', verbose_name='Compañía'),
        ),
    ]
