# Generated by Django 4.2.6 on 2023-11-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_alter_historicaltax_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltax',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicaltaxgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='taxgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
