# Generated by Django 4.2.6 on 2023-10-31 22:53

from django.db import migrations
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
        ('product', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=simple_history.models.HistoricForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='tax.tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_of',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product'),
        ),
        migrations.AddField(
            model_name='listprice',
            name='company',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='company.company'),
        ),
        migrations.AddField(
            model_name='historicalproductprice',
            name='company',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
    ]
