# Generated by Django 4.2.6 on 2023-11-01 10:52

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_alter_historicaltax_options_and_more'),
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicallistprice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Lista de Precios', 'verbose_name_plural': 'historical Listas de Precios'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product', 'verbose_name_plural': 'historical Products'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoria de Producto', 'verbose_name_plural': 'historical Categorias de Producto'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductimage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product Image', 'verbose_name_plural': 'historical Product Images'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductoption',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Opción de Producto', 'verbose_name_plural': 'historical Opciones de Producto'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductprice',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Precio de Producto', 'verbose_name_plural': 'historical Precios de Producto'},
        ),
        migrations.AlterModelOptions(
            name='listprice',
            options={'verbose_name': 'Lista de Precios', 'verbose_name_plural': 'Listas de Precios'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Categoria de Producto', 'verbose_name_plural': 'Categorias de Producto'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'verbose_name': 'Opción de Producto', 'verbose_name_plural': 'Opciones de Producto'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Precio de Producto', 'verbose_name_plural': 'Precios de Producto'},
        ),
        migrations.AlterField(
            model_name='historicallistprice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicallistprice',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='tax',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax.tax', verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='variant_of',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Variante de'),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalproductcategory',
            name='parent',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productcategory', verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='historicalproductimage',
            name='image',
            field=models.TextField(max_length=100, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='historicalproductimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Es Primario'),
        ),
        migrations.AlterField(
            model_name='historicalproductimage',
            name='product',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='historicalproductoption',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalproductoption',
            name='product',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='historicalproductoption',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='historicalproductprice',
            name='list_price',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.listprice', verbose_name='Lista de Precios'),
        ),
        migrations.AlterField(
            model_name='historicalproductprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicalproductprice',
            name='product',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='historicalproductprice',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Válido Desde'),
        ),
        migrations.AlterField(
            model_name='historicalproductprice',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Válido Hasta'),
        ),
        migrations.AlterField(
            model_name='listprice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='listprice',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.productcategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=simple_history.models.HistoricForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='tax.tax', verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant_of',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='Variante de'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_category_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=simple_history.models.HistoricForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.productcategory', verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Es Primario'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='list_price',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.listprice', verbose_name='Lista de Precios'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Válido Desde'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Válido Hasta'),
        ),
    ]
