# Generated by Django 4.2.6 on 2023-11-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
