# Generated by Django 4.2.6 on 2023-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_logo_historicalcompany_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compañía', 'verbose_name_plural': 'Compañías'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompany',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Compañía', 'verbose_name_plural': 'historical Compañías'},
        ),
        migrations.AddField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fantasy Name'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fantasy Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='company',
            name='format_invoice_number',
            field=models.CharField(default='{year}-{month}-{day}-{invoice_number}', help_text='Formato: {year}-{month}-{day}-{invoice_number}', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(help_text='CIF / NIF para facturas', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='address',
            field=models.TextField(verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='format_invoice_number',
            field=models.CharField(default='{year}-{month}-{day}-{invoice_number}', help_text='Formato: {year}-{month}-{day}-{invoice_number}', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='tax_number',
            field=models.CharField(help_text='CIF / NIF para facturas', max_length=255),
        ),
    ]
