# Generated by Django 4.2.6 on 2023-11-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Fantasía'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Fantasía'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
