# Generated by Django 4.2.6 on 2023-11-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_email_alter_company_fantasy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(help_text='CIF / NIF para facturas', max_length=255, verbose_name='Tax Number'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='tax_number',
            field=models.CharField(help_text='CIF / NIF para facturas', max_length=255, verbose_name='Tax Number'),
        ),
    ]
