# Generated by Django 4.2.6 on 2023-11-01 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax', '0005_alter_historicaltax_company_and_more'),
        ('company', '0006_alter_company_tax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company', verbose_name='Cadena'),
        ),
        migrations.AlterField(
            model_name='company',
            name='format_invoice_number',
            field=models.CharField(default='{year}-{month}-{day}-{invoice_number}', help_text='Formato: {year}-{month}-{day}-{invoice_number}', max_length=255, verbose_name='Format Invoice Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(help_text='CIF / NIF para facturas', max_length=255, verbose_name='CIF / NIF'),
        ),
        migrations.AlterField(
            model_name='company',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='companies', to='tax.tax', verbose_name='Impuestos'),
        ),
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='chain',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company', verbose_name='Cadena'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='format_invoice_number',
            field=models.CharField(default='{year}-{month}-{day}-{invoice_number}', help_text='Formato: {year}-{month}-{day}-{invoice_number}', max_length=255, verbose_name='Format Invoice Number'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='tax_number',
            field=models.CharField(help_text='CIF / NIF para facturas', max_length=255, verbose_name='CIF / NIF'),
        ),
    ]
